name: Generate metrics cards
permissions:
contents: write


jobs:
metrics:
runs-on: ubuntu-latest
steps:
# 1) Core profile metrics (languages, topics, follow-up)
- name: Core metrics
uses: lowlighter/metrics@latest
with:
token: ${{ secrets.METRICS_TOKEN }}
user: Shubhamsraut
filename: github-metrics.svg
template: classic
base: header, activity, repositories, metadata
config_timezone: Asia/Kolkata
plugin_languages: yes
plugin_languages_sections: most-used, recently-used
plugin_languages_limit: 8
plugin_languages_ignored: Jupyter Notebook
plugin_topics: yes
plugin_topics_limit: 12
plugin_followup: yes
committer_branch: main
committer_message: "chore: update core metrics"
output_action: commit


# 2) Analyst habits dashboard (heatmap, habits, lines, optional traffic)
- name: Habits & heatmap
uses: lowlighter/metrics@latest
with:
token: ${{ secrets.METRICS_TOKEN }}
user: Shubhamsraut
filename: analytics-habits.svg
template: classic
base: header
config_timezone: Asia/Kolkata
plugin_isocalendar: yes
plugin_isocalendar_duration: full-year
plugin_habits: yes
plugin_habits_facts: yes
plugin_habits_charts: yes
plugin_lines: yes
# Uncomment next line if your PAT has `repo` scope to enable traffic graphs
# plugin_traffic: yes
committer_branch: main
committer_message: "chore: update habits metrics"
output_action: commit


# 3) Achievements strip (compact)
- name: Achievements
uses: lowlighter/metrics@latest
with:
token: ${{ secrets.METRICS_TOKEN }}
user: Shubhamsraut
filename: achievements.svg
template: classic
base: ""
config_timezone: Asia/Kolkata
plugin_achievements: yes
plugin_achievements_threshold: C
plugin_achievements_display: compact
plugin_achievements_secrets: yes
committer_branch: main
committer_message: "chore: update achievements"
output_action: commit
